---
title: "R Notebook"
output: html_notebook
---

This file is to analyze the data i generated with my model 2 in SLiM. 
To be able to simulate 10 runs automatically, I make a slim code bash.
```{r eval=FALSE, include=FALSE}

rm(list=ls(all=TRUE)) #clear R environment

options(scipen = 999) #scientific notation penalty, with this R does not use scientific notation for numbers

setwd("~/Documents/GitHub/2502_emma_bsc") #setting the working directory

reps <- 100
repetition <- seq(1:100)


for(r in 1:reps){
  slim_code_block <- paste0("slim -d repetition=", r, " model2_onlySLiM.slim")
  #slim_code_block 
  system(slim_code_block)#call the code block for slim in the terminal via bash, system invokes the OS command specified by command.
}

```


Now i want to analyze the files/data i just generated

```{r}
#first set the working directory
setwd("~/Documents/GitHub/2502_emma_bsc") 
rm(list=ls(all=TRUE)) #clear R environment

# find all the SLiM output files
files <- list.files(pattern = "model2_reps")


# loop through and extract metrics -> I want relatedness at the beginning and heterozygosity at the end
res_list <- lapply(files, function(f){
  dat <- read.table(f, header = FALSE)  
  data.frame(
    relatedness_start   = dat[1, 2],
    heterozygosity_end  = dat[2, 3]
  )
})

# 4) bind into one data.frame
df <- do.call(rbind, res_list)

# 5) quick base‐R scatterplot
plot(
  df$relatedness_start,
  df$heterozygosity_end,
  xlab = "Starting relatedness",
  ylab = "End heterozygosity",
  main = "Relatedness vs Heterozygosity",
  pch = 19
)

# (optional) add a linear fit
abline(lm(heterozygosity_end ~ relatedness_start, data = df), col = "#54BFB7FF")


# Pearson’s correlation
pearson_res <- cor.test(
  df$relatedness_start,
  df$heterozygosity_end,
  method = "pearson"
)
print(pearson_res)


```



```{r}
library(ggplot2)

ggplot(df, aes(x = relatedness_start, y = heterozygosity_end)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    x    = "Starting relatedness",
    y    = "End heterozygosity",
    title= "Relatedness vs Heterozygosity"
  ) +
  theme_minimal()

```


In this chunk i plot starting heterozygosity vs end heterozygosity
```{r}
#first set the working directory
setwd("~/Documents/GitHub/2502_emma_bsc") 
rm(list=ls(all=TRUE)) #clear R environment

# find all the SLiM output files
files <- list.files(pattern = "model2_reps")


# loop through and extract metrics -> I want relatedness at the beginning and heterozygosity at the end
res_list <- lapply(files, function(f){
  dat <- read.table(f, header = FALSE)  
  data.frame(
    heterozygosity_start   = dat[1, 3],
    heterozygosity_end  = dat[2, 3]
  )
})

# 4) bind into one data.frame
df <- do.call(rbind, res_list)

# 5) quick base‐R scatterplot
plot(
  df$heterozygosity_start,
  df$heterozygosity_end,
  xlab = "Starting heterozygosity",
  ylab = "End heterozygosity",
  main = "starting Heterozygosity vs end heterozygosity",
  pch = 19
)

# (optional) add a linear fit
abline(lm(heterozygosity_end ~ heterozygosity_start, data = df), col = "#54BFB7FF")

# Pearson’s correlation
pearson_res <- cor.test(
  df$heterozygosity_start,
  df$heterozygosity_end,
  method = "pearson"
)
print(pearson_res)

```









