---
title: "Model 2 (cluster)"
author: "Emma Ochsner"
output: html_notebook
---

This notebook is for analyzing the outputs from the model 2 in SLiM. 
The working directory is set to a folder on the server, where i saved my outputs of this simulation.

Change the working directory depending on what data series is analyzed.

```{r}
rm(list=ls(all=TRUE)) #clear R environment

#All of the following were done with recombination rate of 1e-7
#This one is for 8-500 ind, mating for 100 gen
#setwd("/tmp/server_data")

#This one is for 8-500 ind, mating for 5000 generations
#setwd("/tmp/server_data_model25000")

#This one is for 8-100 ind, mating for 1000 generations
#setwd("/tmp/server_data_model2_100_1000")

#This one is for 8-62 ind, mating for 100 gen
#setwd("/tmp/server_data_model2_62_100")

#This one is for 8-62 ind, mating for 100 Gen RANDOM
setwd("/tmp/server_data_model2_62_100_r")

#This one is for a recombination rate of 1e-6 - 8-62 ind, mating for 100 Gen RANDOM
#setwd("/tmp/server_data_1e-6_model2")

#This one is for a recombination rate of 1e-8 - 8-62 ind, mating for 100 Gen RANDOM
#setwd("/tmp/server_data_1e-8_model2")

#This one is for a recombination rate of 1e-9 - 8-62 ind, mating for 100 Gen RANDOM
#setwd("/tmp/server_data_1e-9_model2")

# find all the SLiM output files
files <- list.files(pattern = "model2_reps")


# loop through and extract metrics -> I want to extract relatedness at the beginning and heterozygosity at the end
#lapply applies following function to all the files - i want to define the different values in the files
res_list <- lapply(files, function(f){
  dat <- read.table(f, header = FALSE)  #no header in the files
  data.frame(
    relatedness_start   = dat[1, 2],
    relatedness_end = dat[2,2],
    heterozygosity_start = dat[1,3],
    heterozygosity_end  = dat[2, 3]
  )
})

# bind the values into one data.frame
df <- do.call(rbind, res_list)

```


And now make the plot
```{r}

par(mfrow = c(1,2)) #to have two plots next to each other
# quick base‐R scatterplot (plot)
#First for starting relatedness to end heterozygosity
plot(
  df$relatedness_start,
  df$heterozygosity_end,
  xlab = "Starting relatedness",
  ylab = "End heterozygosity",
  main = "Rel start vs Het end",
  pch = 19,
  cex = 0.4 #make it smaller
)

# add a linear fit (regression line)
abline(lm(heterozygosity_end ~ relatedness_start, data = df), col = "#54BFB7FF", lwd = 2)

text(x = par("usr")[1], y = par("usr")[4], labels = "A", font = 2, cex = 1.1, adj = c(-0.5, 1.5)) 
#par("usr") gives the plot coordinates (so top left corner of the graph - 1 & 4), then labels = ... gives the plot a label, and then make it bold and larger, and adj places the label correctly

# Pearson’s correlation -> test for significant correlation between data points
pearson_res <- cor.test(
  df$relatedness_start,
  df$heterozygosity_end,
  method = "pearson"
)
print(pearson_res)

# quick base‐R scatterplot
#Another one for starting heterozygosity to end heterozygosity
plot(
  df$heterozygosity_start,
  df$heterozygosity_end,
  xlab = "Starting heterozygosity",
  ylab = "End heterozygosity",
  main = "Het start vs Het end",
  pch = 19,
  cex = 0.4
)

# add a linear fit
abline(lm(heterozygosity_end ~ heterozygosity_start, data = df), col = "#54BFB7FF", lwd = 2)

text(x = par("usr")[1], y = par("usr")[4], labels = "B", font = 2, cex = 1.1, adj = c(-0.5, 1.5)) 
#par("usr") gives the plot coordinates (so top left corner of the graph - 1 & 4), then labels = ... gives the plot a label, and then make it bold and larger, and adj places the label correctly

# Pearson’s correlation
pearson_res <- cor.test(
  df$heterozygosity_start,
  df$heterozygosity_end,
  method = "pearson"
)
print(pearson_res)



```

And also plot starting heterozygosity to starting relatedness

```{r}

plot(
  df$relatedness_start,
  df$heterozygosity_start,
  xlab = "Starting relatedness",
  ylab = "starting heterozygosity",
  main = "Relatedness vs Heterozygosity",
  pch = 19,
  cex = 0.4
)

# add a linear fit
abline(lm(heterozygosity_start ~ relatedness_start, data = df), col = "#54BFB7FF", lwd = 2)


# Pearson’s correlation
pearson_res <- cor.test(
  df$relatedness_start,
  df$heterozygosity_start,
  method = "pearson"
)
print(pearson_res)

```

